apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuxt-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nuxt-app
  template:
    metadata:
      labels:
        app: nuxt-app
    spec:
      containers:
      - name: nuxt-container
        image: localhost:5000/nuxt:0.0.4
        ports:
        - containerPort: 3000 # Assuming nuxt runs on port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: nuxt-service
spec:
  selector:
    app: nuxt-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP
